services:
  mock-linear:
    build:
      context: .
      dockerfile: dev/Dockerfile
      args:
        BIN: mock-linear
    ports:
      - "4000:4000"

  mock-gmail:
    build:
      context: .
      dockerfile: dev/Dockerfile
      args:
        BIN: mock-gmail
    ports:
      - "4001:4001"
